# Generated by Django 4.1.7 on 2023-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=300)),
                ('time_taken', models.FloatField(default=0.0)),
                ('title', models.CharField(default='', max_length=255)),
                ('type_visit', models.CharField(default='', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
