# Generated by Django 4.1.7 on 2023-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=300)),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='saveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.JSONField()),
                ('budget', models.IntegerField()),
                ('user', models.CharField(default='', max_length=255)),
                ('save', models.BooleanField(default=False)),
            ],
        ),
    ]
