# Generated by Django 4.1.7 on 2023-03-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_rating_saverecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saverecommendation',
            name='save',
        ),
    ]
