# Generated by Django 4.1.7 on 2023-03-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_saverecommendation_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saverecommendation',
            old_name='destination',
            new_name='recommendations',
        ),
        migrations.RenameField(
            model_name='saverecommendation',
            old_name='budget',
            new_name='total_budget',
        ),
    ]
