# Generated by Django 4.1.7 on 2023-03-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_rename_total_budget_saverecommendation_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
