# Generated by Django 4.1.7 on 2023-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_delete_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=300)),
                ('user', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.CharField(default='', max_length=300),
        ),
    ]
