# Generated by Django 4.1.7 on 2023-03-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_feedback_rating_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='saverecommendation',
            name='budget',
        ),
    ]
